### ISSUE TITLE
Can you set chmod +x on install.sh?

### ISSUE THREAD

**Issue by SolarAquarion** [weltensturm/flatman#6]

**Comment by SolarAquarion** [comment]
Building wm
../../../../../.dub/packages/x11-1.0.20/x11/source/x11/extensions/XI.d(3,8): Deprecation: Symbol object.string is not visible from module XI because it is privately imported in module string
Building compositor
../../../../../.dub/packages/x11-1.0.20/x11/source/x11/extensions/XI.d(3,8): Deprecation: Symbol object.string is not visible from module XI because it is privately imported in module string
Building dock
../../../../../.dub/packages/x11-1.0.20/x11/source/x11/extensions/XI.d(3,8): Deprecation: Symbol object.string is not visible from module XI because it is privately imported in module string
src/dock.d(428,35): Error: storing reference to stack allocated value returned by digest(n) into allocated memory causes it to escape

@weltensturm

**Comment by weltensturm** [comment]
fixed on dev branch
